# .readthedocs.yaml
# RTD configuration file for building Django project documentation with Sphinx

version: 2  # RTD configuration version

# -----------------------------
# Build environment
# -----------------------------
build:
  os: ubuntu-22.04        # Operating system for the build
  tools:
    python: "3.12"        # Python version to use

# -----------------------------
# Python environment setup
# -----------------------------
python:
  install:
    # Install project dependencies from requirements.txt
    - requirements: requirements.txt
    # Install the project itself in editable mode
    - path: "."  # Ensures Django modules are importable

# -----------------------------
# Sphinx configuration
# -----------------------------
sphinx:
  configuration: docs/conf.py   # Path to your Sphinx config
  builder: "html"               # Build HTML documentation

# -----------------------------
# Output formats
# -----------------------------
formats:
  - "htmlzip"   # Valid formats: htmlzip, pdf, epub

# -----------------------------
# Environment variables
# -----------------------------
env:
  # Required for Django to find settings
  DJANGO_SETTINGS_MODULE: "oc_lettings_site.settings"
  # Add project root to PYTHONPATH so Django imports work
  PYTHONPATH: "../"
