# .readthedocs.yaml
# RTD configuration file for building Django project documentation with Sphinx
version: 2

# -----------------------------
# Build environment
# -----------------------------
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  # Variables d'environnement définies ici
  env:
    DJANGO_SETTINGS_MODULE: "oc_lettings_site.settings"
    PYTHONPATH: "/checkouts"

# -----------------------------
# Python environment setup
# -----------------------------
python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

# -----------------------------
# Sphinx configuration
# -----------------------------
sphinx:
  configuration: docs/conf.py
  builder: html

# -----------------------------
# Output formats
# -----------------------------
formats:
  - htmlzip
