# .readthedocs.yaml
version: 2  # RTD configuration version

# Build environment
build:
  os: ubuntu-22.04  # Operating system
  tools:
    python: "3.12"  # Python version

# Python environment setup
python:
  install:
    # Install dependencies from requirements.txt
    - requirements: requirements.txt
    # Install the project itself
    - path: "."  # this installs your Django project as editable

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  builder: "html"

# Output formats
formats:
  - "htmlzip"  # allowed formats: htmlzip, pdf, epub

# Environment variables to configure Django properly
env:
  DJANGO_SETTINGS_MODULE: "oc_lettings_site.settings"
  PYTHONPATH: "../"  # Ensure Django project root is in Python path
