# .readthedocs.yaml
version: 2  # RTD configuration version

# Build environment
build:
  os: ubuntu-22.04  # Operating system
  tools:
    python: "3.12"  # Python version

# Python environment setup
python:
  install:
    # Install the project itself
    - method: pip
      path: .
    # Install dependencies from requirements.txt
    - requirements: requirements.txt
    # Optional: install extra dev dependencies if defined
    - extra_requirements:
        - dev

# Sphinx configuration
sphinx:
  # Path to the Sphinx configuration file
  configuration: docs/conf.py
  # Optionally, set builder format (default is html)
  builder: "html"

# Output formats
formats:
  - "htmlzip"  # Must be one of htmlzip, pdf, epub

# Environment variables to configure Django properly
env:
  DJANGO_SETTINGS_MODULE: "oc_lettings_site.settings"
  PYTHONPATH: "../"  # Ensure Django project root is in Python path

# Optional build commands (advanced setup)
# build:
#   commands:
#     - python manage.py collectstatic --noinput
#     - sphinx-build -b html docs/ docs/_build/html
